# Site settings
title: Craig Weston - Travel Blog
email: craig.weston1@hotmail.co..uk
description: My simple blog.
baseurl: "/travel-blog"
url: ""
twitter_username: craigweston_
avatar: "https://pbs.twimg.com/profile_images/507229858171453440/OdpYI3lp.jpeg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Craig" # Set default author name
      categories: "places"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
